// src/pages/CachePage.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted, watch } from 'vue'
import { TxCard } from '@talex-touch/tuffex/card'
import { TxDataTable } from '@talex-touch/tuffex/data-table'
import { TxTag } from '@talex-touch/tuffex/tag'
import { TxButton } from '@talex-touch/tuffex/button'
import { TxStatusBadge } from '@talex-touch/tuffex/status-badge'
import { TxEmptyState } from '@talex-touch/tuffex/empty-state'
import { TxSelect, TxSelectItem } from '@talex-touch/tuffex/select'
import PageHeader from '../components/PageHeader.vue'
import ErrorPanel from '../components/ErrorPanel.vue'
import LoadingBlock from '../components/LoadingBlock.vue'
import { CLIENT_LABELS } from '../clientLabels'
import { channelLabel } from '../channelLabels'
import { api } from '../api'
import { useQueryState } from '../lib/listState'
import { useResource } from '../lib/resource'
import { fmtClock, fmtCompact, fmtLatency, fmtPercent, fmtUsd } from '../lib/format'
import type { ApiKeyItem, CacheTrendData, CacheTrendProvider, LiveUsageEvent } from '../types'

/** 模型/客户端/渠道/时间范围全部进 URL：刷新与分享链接保持同一视图（红队 D13）。 */
const scope = useQueryState({ hours: '24', model: '', client: '', keyId: '', provider: '' })
const hours = computed(() => {
  const value = Number(scope.state.hours)
  return [1, 6, 24, 72, 168].includes(value) ? value : 24
})

type BootstrapPayload = { keys?: ApiKeyItem[] }
const keysRes = useResource(() => api.bootstrap<BootstrapPayload>(), [])

const trendRes = useResource(
  () =>
    api.cacheTrend<CacheTrendData>(
      hours.value,
      scope.state.model,
      scope.state.client,
      scope.state.keyId,
      scope.state.provider,
    ),
  [() => scope.state.hours, () => scope.state.model, () => scope.state.client, () => scope.state.keyId, () => scope.state.provider],
)

const error = computed(() => trendRes.error.value ?? keysRes.error.value)
const reloadAll = () => Promise.all([trendRes.reload(), keysRes.reload()])

const internalTrend = computed(() => trendRes.data.value)
const internalModels = computed(() => internalTrend.value?.models ?? [])
const internalClients = computed(() => internalTrend.value?.clients ?? [])
const internalProviders = computed(() => internalTrend.value?.providers ?? [])

const liveEvents = ref<LiveUsageEvent[]>([])
const sseConnected = ref(false)
let eventSource: EventSource | null = null
let reconnectTimer: ReturnType<typeof setTimeout> | null = null

/** 统一格式化：实现都在 src/lib/format.ts（红队 D16：同一数字不再有两个单位）。 */
const tokens = fmtCompact
const money = (value: number | null | undefined) => (value === null || value === undefined ? 'n/a' : fmtUsd(value))
const percent = (value: number | null | undefined) => (value === null || value === undefined ? 'n/a' : fmtPercent(value))
const clock = (iso: string) => fmtClock(iso)

const hitToneColor = (rate: number | null) => {
  if (rate === null) return '#8a90b0'
  if (rate >= 0.9) return '#10b981'
  if (rate >= 0.7) return '#f59e0b'
  return '#ef4444'
}

function setupSSE() {
  if (eventSource) {
    eventSource.close()
    eventSource = null
  }
  liveEvents.value = []
  const url = api.cacheLiveUrl(60, scope.state.model, scope.state.client, scope.state.keyId, scope.state.provider)
  eventSource = new EventSource(url)
  eventSource.addEventListener('open', () => {
    sseConnected.value = true
  })
  eventSource.addEventListener('history', (e) => {
    try {
      const rows = JSON.parse((e as MessageEvent).data) as LiveUsageEvent[]
      sseConnected.value = true
      liveEvents.value = rows.slice(-200).reverse()
    } catch {
      /* 单条事件解析失败不影响整体流 */
    }
  })
  eventSource.addEventListener('usage', (e) => {
    try {
      const rows = JSON.parse((e as MessageEvent).data) as LiveUsageEvent[]
      liveEvents.value = [...rows.reverse(), ...liveEvents.value].slice(0, 200)
    } catch {
      /* 同上 */
    }
  })
  // 断线不再无限静默：状态可见（「重连中」徽章）并自动重连一次（红队未验证项 8）。
  eventSource.addEventListener('error', () => {
    sseConnected.value = false
    if (eventSource) {
      eventSource.close()
      eventSource = null
    }
    if (reconnectTimer) clearTimeout(reconnectTimer)
    reconnectTimer = setTimeout(() => setupSSE(), 5000)
  })
}

watch(
  [() => scope.state.hours, () => scope.state.model, () => scope.state.client, () => scope.state.keyId, () => scope.state.provider],
  () => setupSSE(),
)

onMounted(() => {
  setupSSE()
})

onUnmounted(() => {
  if (eventSource) {
    eventSource.close()
    eventSource = null
  }
  if (reconnectTimer) {
    clearTimeout(reconnectTimer)
    reconnectTimer = null
  }
})

const points = computed(() => internalTrend.value?.points ?? [])

const totalHitRate = computed(() => {
  if (!points.value.length) return null
  const cacheRead = points.value.reduce((s, p) => s + p.cacheReadTokens, 0)
  const denominator = points.value.reduce((s, p) => s + p.cacheReadTokens + p.freshInputTokens + (p.cacheWriteTokens || 0), 0)
  return denominator > 0 ? cacheRead / denominator : null
})

const totalCost = computed(() => points.value.reduce((s, p) => s + (p.costUsd ?? 0), 0))
const totalRequests = computed(() => points.value.reduce((s, p) => s + p.requests, 0))
const liveCost = computed(() => liveEvents.value.reduce((s, e) => s + (e.costUsd ?? 0), 0))

// SVG 趋势图坐标生成
const svgPoints = computed(() => {
  if (!points.value.length) return ''
  const w = 800
  const h = 180
  const pts = points.value
  const step = w / Math.max(1, pts.length - 1)
  return pts.map((p, idx) => {
    const x = idx * step
    const y = h - (p.hitRate !== null ? p.hitRate : 0) * h * 0.9 - 10
    return `${x},${y}`
  }).join(' ')
})

const liveColumns = [
  { key: 'time', title: '时间', width: 90 },
  { key: 'model', title: '模型', width: 180 },
  { key: 'key', title: 'Key', width: 120 },
  { key: 'client', title: '客户端', width: 120 },
  { key: 'input', title: '输入', width: 90, align: 'right' as const },
  { key: 'output', title: '输出', width: 90, align: 'right' as const },
  { key: 'cacheRead', title: '缓存读', width: 90, align: 'right' as const },
  { key: 'cacheWrite', title: '缓存写', width: 90, align: 'right' as const },
  { key: 'hitRate', title: '命中率', width: 90, align: 'center' as const },
  { key: 'cost', title: '花费', width: 90, align: 'right' as const },
  { key: 'latency', title: '耗时', width: 80, align: 'right' as const },
]
</script>

<template>
  <div class="page-stack cache-page">
    <PageHeader
      title="缓存命中率分析"
      description="监控各时间段的提示词缓存命中率趋势，以及每一条在线请求的实际命中与花费明细；筛选条件写在地址栏里。"
    >
      <template #actions>
        <TxSelect :model-value="scope.state.model" placeholder="选择模型" class="w-160px" @update:model-value="v => (scope.state.model = String(v))">
          <TxSelectItem value="" label="全部模型" />
          <TxSelectItem v-for="m in internalModels" :key="m" :value="m" :label="m" />
        </TxSelect>
        <TxSelect :model-value="scope.state.client" placeholder="选择客户端" class="w-140px" @update:model-value="v => (scope.state.client = String(v))">
          <TxSelectItem value="" label="全部客户端" />
          <TxSelectItem v-for="c in internalClients" :key="c.type" :value="c.type" :label="`${c.label} (${tokens(c.requests)})`" />
        </TxSelect>
        <TxSelect :model-value="scope.state.provider" placeholder="选择渠道" class="w-130px" @update:model-value="v => (scope.state.provider = String(v))">
          <TxSelectItem value="" label="全部渠道" />
          <TxSelectItem v-for="p in internalProviders" :key="p.id" :value="p.id" :label="`${channelLabel(p.id)} (${tokens(p.requests)})`" />
        </TxSelect>
        <TxSelect :model-value="scope.state.hours" placeholder="时间范围" class="w-130px" @update:model-value="v => (scope.state.hours = String(v))">
          <TxSelectItem value="1" label="最近 1 小时" />
          <TxSelectItem value="6" label="最近 6 小时" />
          <TxSelectItem value="24" label="最近 24 小时" />
          <TxSelectItem value="72" label="最近 3 天" />
          <TxSelectItem value="168" label="最近 7 天" />
        </TxSelect>
        <TxButton variant="secondary" :loading="trendRes.loading.value" @click="reloadAll">
          刷新
        </TxButton>
      </template>
    </PageHeader>

    <!-- 失败：可读原因 + 重试；首次加载：骨架；其余：保留旧数据继续渲染 -->
    <ErrorPanel v-if="error" :error="error" :retry="reloadAll" />
    <LoadingBlock v-else-if="!internalTrend" :lines="7" label="正在读取缓存命中率" />

    <template v-else>
    <!-- 顶部汇总指标卡 -->
    <div class="metric-row">
      <TxCard class="stat-box">
        <span class="stat-label">区间总命中率</span>
        <strong class="stat-value mono" :style="{ color: hitToneColor(totalHitRate) }">{{ percent(totalHitRate) }}</strong>
        <small class="stat-sub">{{ fmtCompact(totalRequests) }} 次请求</small>
      </TxCard>
      <TxCard class="stat-box">
        <span class="stat-label">区间总成本</span>
        <strong class="stat-value mono">{{ money(totalCost) }}</strong>
        <small class="stat-sub">最近 {{ hours }} 小时</small>
      </TxCard>
      <TxCard class="stat-box">
        <span class="stat-label">实时流花费</span>
        <strong class="stat-value mono">{{ money(liveCost) }}</strong>
        <small class="stat-sub">当前流水 {{ liveEvents.length }} 条</small>
      </TxCard>
    </div>

    <!-- 命中率趋势折线图 -->
    <TxCard :padding="16">
      <template #header>
        <div class="card-head">
          <strong>命中率趋势</strong>
          <span class="count">{{ internalTrend?.bucketSeconds ? `${internalTrend.bucketSeconds / 60} 分钟/档` : '趋势时序' }}</span>
        </div>
      </template>

        <div class="chart-container">
        <svg v-if="points.length > 1" viewBox="0 0 800 200" class="trend-svg" preserveAspectRatio="none" role="img" aria-label="缓存命中率趋势">
          <defs>
            <linearGradient id="trendGrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stop-color="#10b981" stop-opacity="0.35" />
              <stop offset="100%" stop-color="#10b981" stop-opacity="0.02" />
            </linearGradient>
          </defs>
          <!-- 面积渐变填充 -->
          <polygon :points="`0,200 ${svgPoints} 800,200`" fill="url(#trendGrad)" />
          <!-- 折线 -->
          <polyline :points="svgPoints" fill="none" stroke="#10b981" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
        <div v-else class="text-muted text-center py-8">
          当前区间请求不够，画不出折线；把时间范围调长一些。
        </div>
      </div>
    </TxCard>

    <!-- 实时请求流 -->
    <TxCard :padding="16">
      <template #header>
        <div class="card-head">
          <div class="flex items-center gap-2">
            <strong>实时请求流</strong>
            <TxStatusBadge :status="sseConnected ? 'success' : 'warning'" :text="sseConnected ? '实时已连接' : '重连中'" size="sm" />
          </div>
          <span class="count">最新 200 条请求实时刷新</span>
        </div>
      </template>

      <TxDataTable
        :columns="liveColumns"
        :data="liveEvents"
        row-key="requestId"
        striped
        bordered
        class="live-table"
      >
        <template #cell-time="{ row }">
          <span class="mono text-xs text-muted">{{ clock(row.timestamp) }}</span>
        </template>
        <template #cell-model="{ row }">
          <strong class="mono text-xs" :title="row.model">{{ row.model }}</strong>
        </template>
        <template #cell-key="{ row }">
          <span class="text-xs" :title="row.keyName || row.source">{{ row.keyName || row.source || '—' }}</span>
        </template>
        <template #cell-client="{ row }">
          <span class="text-xs text-muted">{{ CLIENT_LABELS[row.clientType || 'unknown'] || '未知' }}</span>
        </template>
        <template #cell-input="{ row }">
          <span class="mono text-xs">{{ tokens(row.inputTokens || 0) }}</span>
        </template>
        <template #cell-output="{ row }">
          <span class="mono text-xs">{{ tokens(row.outputTokens || 0) }}</span>
        </template>
        <template #cell-cacheRead="{ row }">
          <span class="mono text-xs">{{ tokens(row.cacheReadTokens || 0) }}</span>
        </template>
        <template #cell-cacheWrite="{ row }">
          <span class="mono text-xs">{{ tokens(row.cacheWriteTokens || 0) }}</span>
        </template>
        <template #cell-hitRate="{ row }">
          <TxTag
            :label="percent(row.hitRate)"
            :color="hitToneColor(row.hitRate)"
            size="sm"
            variant="soft"
            class="mono"
          />
        </template>
        <template #cell-cost="{ row }">
          <span class="mono text-xs font-semibold">{{ money(row.costUsd) }}</span>
        </template>
        <template #cell-latency="{ row }">
          <span class="mono text-xs">{{ fmtLatency(row.latencyMs) }}</span>
        </template>
        <template #empty>
          <TxEmptyState
            title="等待请求接入…"
            description="当客户端发送 API 调用时，事件会自动出现在这里；若长时间没有数据，请检查上游渠道是否在接流量。"
            size="small"
          />
        </template>
      </TxDataTable>
    </TxCard>
    </template>
  </div>
</template>

<style scoped>
.cache-page {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;
}
.page-head {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  justify-content: space-between;
  gap: 16px;
}
.page-head__text h1 {
  margin: 0;
  font-size: 24px;
  font-weight: 700;
  color: var(--tx-text-color-primary, #151b45);
}
.page-head__text p {
  margin: 4px 0 0;
  color: var(--tx-text-color-secondary, #535b85);
  font-size: 13.5px;
}
.eyebrow {
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.05em;
  color: var(--tx-color-primary, #3346c8);
  margin-bottom: 2px;
}
.page-head__actions {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 10px;
}
.w-160px { width: 160px; }
.w-140px { width: 140px; }
.w-130px { width: 130px; }
.metric-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
}
.stat-box {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.stat-label {
  font-size: 12px;
  color: var(--tx-text-color-secondary, #535b85);
}
.stat-value {
  font-size: 24px;
  font-weight: 700;
}
.stat-sub {
  font-size: 11.5px;
  color: var(--tx-text-color-placeholder, #8a90b0);
}
.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}
.card-head .count {
  font-size: 12px;
  color: var(--tx-text-color-secondary, #535b85);
}
.chart-container {
  height: 200px;
  width: 100%;
  position: relative;
}
.trend-svg {
  width: 100%;
  height: 100%;
}
.live-table {
  width: 100%;
}
.mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
.text-xs { font-size: 11.5px; }
.text-muted { color: var(--tx-text-color-placeholder, #8a90b0); }
.font-semibold { font-weight: 600; }
</style>

// src/pages/CachePage.tsx
import { Coins, Gauge, Radio, RefreshCw, Zap } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Select } from '../components/Select'
import { CLIENT_LABELS } from '../clientLabels'
import { AXIS, STATUS } from '../chartTheme'
import { api } from '../api'
import { channelLabel } from '../channelLabels'
import type { ApiKeyItem, CacheTrendData, CacheTrendProvider, LiveUsageEvent } from '../types'

const tokens = (value: number) => {
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(1)}B`
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`
  return value.toLocaleString('zh-CN')
}

/** 单请求金额通常是几分钱，固定两位小数会全变成 $0.00，所以小额保留更多位。 */
const money = (value: number | null) => {
  if (value === null) return 'n/a'
  if (value === 0) return '$0'
  if (value < 0.01) return `$${value.toFixed(5)}`
  if (value < 1) return `$${value.toFixed(4)}`
  return `$${value.toFixed(2)}`
}

const percent = (value: number | null) => (value === null ? 'n/a' : `${(value * 100).toFixed(1)}%`)

const hitTone = (rate: number | null) => {
  if (rate === null) return 'na'
  if (rate >= 0.9) return 'good'
  if (rate >= 0.7) return 'warn'
  return 'bad'
}

const clock = (iso: string) => {
  const d = new Date(iso)
  return Number.isNaN(d.getTime())
    ? iso
    : `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}:${String(d.getSeconds()).padStart(2, '0')}`
}

const bucketLabel = (iso: string, bucketSeconds: number) => {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  const hm = `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`
  return bucketSeconds >= 86_400 ? `${d.getMonth() + 1}/${d.getDate()}` : hm
}

function TrendTooltip({ active, payload, bucketSeconds }: { active?: boolean; payload?: Array<{ payload: CacheTrendData['points'][number] }>; bucketSeconds: number }) {
  if (!active || !payload?.length) return null
  const p = payload[0].payload
  const d = new Date(p.bucket)
  return (
    <div className="chart-tip">
      <strong>{Number.isNaN(d.getTime()) ? p.bucket : d.toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })}</strong>
      <span>命中率 <b className={`hit-${hitTone(p.hitRate)}`}>{percent(p.hitRate)}</b></span>
      <span>请求 {p.requests.toLocaleString('zh-CN')} 次</span>
      <span>成本 {money(p.costUsd)}</span>
      <span>新输入 {tokens(p.freshInputTokens)}</span>
      <span>缓存读 {tokens(p.cacheReadTokens)}</span>
      <span>缓存写入 {tokens(p.cacheWriteTokens || 0)}</span>
      <span className="chart-tip-foot">{bucketSeconds >= 3600 ? `${bucketSeconds / 3600} 小时` : `${bucketSeconds / 60} 分钟`}一档</span>
    </div>
  )
}

export function CachePage({
  trend,
  loading,
  hours,
  model,
  models,
  client,
  clients,
  keys,
  keyId,
  onKey,
  providers,
  provider,
  onProvider,
  onClient,
  onHours,
  onModel,
  onRefresh,
}: {
  trend: CacheTrendData | null
  loading: boolean
  hours: number
  model: string
  models: string[]
  client: string
  clients: Array<{ type: string; label: string; requests: number }>
  /** bootstrap.keys：按 Key 看命中率时的选项来源 */
  keys: ApiKeyItem[]
  keyId: string
  onKey: (keyId: string) => void
  /** 趋势接口返回的各渠道请求量 */
  providers: CacheTrendProvider[]
  provider: string
  onProvider: (provider: string) => void
  onClient: (client: string) => void
  onHours: (hours: number) => void
  onModel: (model: string) => void
  onRefresh: () => void
}) {
  const [live, setLive] = useState<LiveUsageEvent[]>([])
  const [connected, setConnected] = useState(false)

  // SSE 长连接：首帧回放历史，之后接收增量。断线由浏览器按 retry 自动重连。
  // 依赖全部筛选条件：切换时重建连接，让实时流与上方趋势图保持同一口径。
  useEffect(() => {
    setLive([])
    const source = new EventSource(api.cacheLiveUrl(60, model, client, keyId, provider))
    source.addEventListener('open', () => setConnected(true))
    source.addEventListener('history', (event) => {
      const rows = JSON.parse((event as MessageEvent).data) as LiveUsageEvent[]
      setConnected(true)
      setLive(rows.slice(-200).reverse())
    })
    source.addEventListener('usage', (event) => {
      const rows = JSON.parse((event as MessageEvent).data) as LiveUsageEvent[]
      // 上限 200 条：无上限会让长时间挂着的页面越来越卡
      setLive((prev) => [...rows.reverse(), ...prev].slice(0, 200))
    })
    source.addEventListener('error', () => setConnected(false))
    return () => source.close()
  }, [model, client, keyId, provider])

  const points = trend?.points ?? []
  // 分母必须含缓存写入段，否则首次写缓存的请求会被算成满命中，
  // claude 系列会恒显示 100.0%（与服务端 hitRate() 口径保持一致）。
  const totalHit = points.length
    ? points.reduce((s, p) => s + p.cacheReadTokens, 0) /
      Math.max(1, points.reduce((s, p) => s + p.cacheReadTokens + p.freshInputTokens + (p.cacheWriteTokens || 0), 0))
    : null
  const totalCost = points.reduce((s, p) => s + (p.costUsd ?? 0), 0)
  const totalReq = points.reduce((s, p) => s + p.requests, 0)
  const liveCost = live.reduce((s, e) => s + (e.costUsd ?? 0), 0)

  const chartData = points.map((p) => ({ ...p, label: bucketLabel(p.bucket, trend?.bucketSeconds ?? 900), pct: p.hitRate === null ? null : p.hitRate * 100 }))
  const modelOptions = model && !models.includes(model) ? [model, ...models] : models
  const clientOptions = client && !clients.some((item) => item.type === client)
    ? [{ type: client, label: CLIENT_LABELS[client] || client, requests: 0 }, ...clients]
    : clients
  const keyOptions = keyId && !keys.some((item) => item.id === keyId)
    ? [{ id: keyId, name: `已删除 Key ${keyId.slice(0, 8)}` }, ...keys]
    : keys
  const providerOptions = provider && !providers.some((item) => item.id === provider)
    ? [{ id: provider, label: channelLabel(provider), requests: 0 }, ...providers]
    : providers

  const cards = [
    { label: '区间总命中率', value: percent(totalHit), meta: `${totalReq.toLocaleString('zh-CN')} 次请求`, icon: Gauge, tone: 'mint', strongClass: `hit-${hitTone(totalHit)}` },
    { label: '区间总成本', value: money(totalCost), meta: `最近 ${hours} 小时`, icon: Coins, tone: 'blue' },
    { label: '实时流成本', value: money(liveCost), meta: `当前 ${live.length} 条`, icon: Zap, tone: 'amber' },
  ]

  return (
    <div className="page-stack">
      <section className="page-heading">
        <div>
          <p className="eyebrow">CACHE PERFORMANCE</p>
          <h1>缓存命中率</h1>
          <p>各时间段的总命中率趋势，以及每一次请求的实时命中率与花费。</p>
        </div>
        <div className="heading-filters">
          <Select ariaLabel="选择模型" value={model} onChange={onModel}
            options={[{ value: '', label: '全部模型' }, ...modelOptions.map((m) => ({ value: m, label: m }))]} />
          <Select ariaLabel="选择客户端" value={client} onChange={onClient}
            options={[{ value: '', label: '全部客户端' }, ...clientOptions.map((item) => ({ value: item.type, label: `${item.label} · ${tokens(item.requests)}` }))]} />
          <Select ariaLabel="选择 API Key" value={keyId} onChange={onKey}
            options={[{ value: '', label: '全部 Key' }, ...keyOptions.map((item) => ({ value: item.id, label: item.name }))]} />
          <Select ariaLabel="选择渠道" value={provider} onChange={onProvider}
            options={[{ value: '', label: '全部渠道' }, ...providerOptions.map((item) => ({ value: item.id, label: `${item.label} · ${tokens(item.requests)}` }))]} />
          <Select ariaLabel="选择时间范围" value={String(hours)} onChange={(v) => onHours(Number(v))}
            options={[
              { value: '1', label: '最近 1 小时' },
              { value: '6', label: '最近 6 小时' },
              { value: '24', label: '最近 24 小时' },
              { value: '72', label: '最近 3 天' },
              { value: '168', label: '最近 7 天' },
              { value: '336', label: '最近 14 天' },
              { value: '720', label: '最近 30 天' },
              { value: '2160', label: '最近 90 天' },
            ]} />
          <button type="button" className="icon-button" onClick={onRefresh} title="刷新">
            <RefreshCw size={17} className={loading ? 'spin' : ''} />
          </button>
        </div>
      </section>

      <section className="metric-grid metric-grid-3">
        {cards.map(({ label, value, meta, icon: Icon, tone, strongClass }) => (
          <article className="metric-card" key={label}>
            <div className={`metric-icon ${tone}`}><Icon size={19} /></div>
            <p>{label}</p><strong className={strongClass}>{value}</strong><span>{meta}</span>
          </article>
        ))}
      </section>

      <article className="panel">
        <div className="panel-title">
          <div><h2>命中率趋势</h2><p>每档时间区间的总命中率，用于定位命中率下滑的时段</p></div>
          <span className="soft-badge">{trend ? (trend.bucketSeconds >= 3600 ? `${trend.bucketSeconds / 3600}h/档` : `${trend.bucketSeconds / 60}min/档`) : '—'}</span>
        </div>
        <div className="trend-wrap">
          {chartData.length === 0 ? (
            <p className="cache-empty">{loading ? '加载中…' : '该区间没有请求'}</p>
          ) : (
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData} margin={{ top: 6, right: 12, bottom: 0, left: 0 }}>
                <defs>
                  <linearGradient id="hitFill" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={STATUS.good} stopOpacity={0.28} />
                    <stop offset="100%" stopColor={STATUS.good} stopOpacity={0.02} />
                  </linearGradient>
                </defs>
                <CartesianGrid stroke={AXIS.grid} vertical={false} />
                <XAxis dataKey="label" tick={{ fill: AXIS.tick, fontSize: 11 }} tickLine={false} axisLine={false} minTickGap={28} />
                <YAxis domain={[0, 100]} unit="%" tick={{ fill: AXIS.tick, fontSize: 11 }} tickLine={false} axisLine={false} width={44} />
                <Tooltip content={<TrendTooltip bucketSeconds={trend?.bucketSeconds ?? 900} />} />
                <Area type="monotone" dataKey="pct" stroke={STATUS.good} strokeWidth={2} fill="url(#hitFill)" connectNulls={false} dot={false} isAnimationActive={false} />
              </AreaChart>
            </ResponsiveContainer>
          )}
        </div>
      </article>

      <article className="panel">
        <div className="panel-title">
          <div>
            <h2>实时请求流</h2>
            <p>每一次请求的命中率与花费，新请求自动出现在最上方</p>
          </div>
          <span className={`live-dot-badge ${connected ? 'on' : 'off'}`}>
            <Radio size={13} />{connected ? '实时' : '重连中'}
          </span>
        </div>
        {live.length === 0 ? (
          <p className="cache-empty">等待请求…发一条请求即可看到它出现在这里。</p>
        ) : (
          <div className="cache-table scroll-area live-table">
            <div className="cache-row live-row cache-head">
              <span>时间</span><span>模型</span><span>Key</span><span>客户端</span><span className="num">输入</span><span className="num">输出</span>
              <span className="num">上下文</span><span className="num">缓存读</span><span className="num">缓存写</span><span>命中率</span><span className="num">花费</span><span className="num">耗时</span>
            </div>
            {live.map((e) => (
              <div className={`cache-row live-row${e.overCeiling ? ' alert' : ''}${e.success ? '' : ' failed'}`} key={e.requestId}>
                <span className="req-time">{clock(e.timestamp)}</span>
                <strong title={`${e.model} · ${channelLabel(e.provider || '')} · ${e.endpoint}`}>{e.model}</strong>
                {/* 直接显示 Key 名，才能一眼看出是谁的请求在拖低命中率。 */}
                <span className="req-key" title={e.keyName || e.source || '未关联 Key'}>{e.keyName || e.source || '—'}</span>
                <span className="req-client" title={e.userAgent || '未上报'}>{CLIENT_LABELS[e.clientType || 'unknown'] || '未知'}</span>
                <span className="num">{tokens(e.inputTokens || 0)}</span>
                <span className="num">{tokens(e.outputTokens || 0)}</span>
                <span className="num">
                  {tokens(e.promptTokens)}
                  {e.overCeiling && <em className="over-pill inline">超限</em>}
                </span>
                {/* 缓存写入比「新输入」更有诊断价值：Anthropic 的新输入恒为个位数，
                    真正花钱的是反复重建的缓存写入段。 */}
                <span className="num">{tokens(e.cacheReadTokens || 0)}</span>
                <span className="num">{tokens(e.cacheWriteTokens || 0)}</span>
                <span className={`hit-chip ${hitTone(e.hitRate)}`}>{percent(e.hitRate)}</span>
                <span className="num money">{money(e.costUsd)}</span>
                <span className="num">{(e.latencyMs / 1000).toFixed(1)}s</span>
              </div>
            ))}
          </div>
        )}
      </article>
    </div>
  )
}
