// src/pages/MonitorPage.tsx
import { Activity, Cloud, Crown, RefreshCw, RotateCcw, ShieldCheck, TriangleAlert, Users } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { ResultDialog } from '../components/ResultDialog'
import type { AccountQuota, MonitorData, QuotaShareWindow, QuotaWindow } from '../types'

const PROVIDERS: Record<string, { label: string; logo: string; className: string }> = {
  claude: { label: 'Claude', logo: 'AI', className: 'claude' },
  codex: { label: 'Codex', logo: 'O', className: 'codex' },
  antigravity: { label: 'AntiGravity', logo: 'AG', className: 'antigravity' },
}

const PROVIDER_ORDER = ['antigravity', 'claude', 'codex']

const expiryClock = (value: string) => {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

/** 剩余时间用「还有 2 天 3 小时」这种粗粒度描述，比精确到分钟更符合看额度的场景。 */
function untilReset(resetsAt: string | null): string {
  if (!resetsAt) return ''
  const target = new Date(resetsAt).getTime()
  if (Number.isNaN(target)) return ''
  const minutes = Math.round((target - Date.now()) / 60000)
  if (minutes <= 0) return '即将重置'
  if (minutes < 60) return `还有 ${minutes} 分钟`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `还有 ${hours} 小时${minutes % 60 ? ` ${minutes % 60} 分钟` : ''}`
  const days = Math.floor(hours / 24)
  return `还有 ${days} 天${hours % 24 ? ` ${hours % 24} 小时` : ''}`
}

const resetClock = (resetsAt: string | null) => {
  if (!resetsAt) return ''
  const date = new Date(resetsAt)
  if (Number.isNaN(date.getTime())) return ''
  return date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

const compactTokens = (value: number) => {
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(1)}B`
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}k`
  return value.toLocaleString('zh-CN')
}

const windowStartClock = (windowStart: number) => {
  const date = new Date(windowStart)
  if (Number.isNaN(date.getTime())) return ''
  return date.toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

/**
 * 「本窗口各 Key 消耗占比」。套餐额度不按美元计量、缓存读同样吃额度，
 * 所以这里只按 token 体量（输入 + 缓存 + 输出）算相对占比，回答「额度被谁用掉了」。
 */
function QuotaShareList({ share }: { share: QuotaShareWindow | undefined | null }) {
  if (!share) return null
  const since = windowStartClock(share.windowStart)
  const rows = share.keys.slice(0, 12)
  const rest = share.keys.length - rows.length
  return <section className="quota-share" aria-label="本窗口各 Key 消耗占比">
    <div className="quota-share-head">
      <h3><Users size={13} /> 本窗口各 Key 消耗占比</h3>
      <span>{since ? `自 ${since} 起` : ''} · 按 token 体量（输入 + 缓存 + 输出）</span>
    </div>
    {rows.length === 0
      ? <p className="quota-share-empty">本窗口内还没有成功请求</p>
      : <div className="quota-share-list">
        {rows.map((key, index) => <div className={index === 0 ? 'quota-share-row top' : 'quota-share-row'} key={key.keyId || key.keyName}>
          <strong title={`${key.requests.toLocaleString('zh-CN')} 次请求 · 提示 ${compactTokens(key.promptTokens)} · 输出 ${compactTokens(key.outputTokens)}`}>{key.keyName}</strong>
          <div className="progress-track"><span style={{ width: `${Math.max(1, Math.round(key.share * 100))}%` }} /></div>
          <em>{(key.share * 100).toFixed(1)}%</em>
        </div>)}
        {rest > 0 && <p className="quota-share-empty">还有 {rest} 个 Key 占比更低，未展开</p>}
      </div>}
  </section>
}

function QuotaRow({ window }: { window: QuotaWindow }) {
  const remaining = Math.max(0, 100 - window.usedPercent)
  const clock = resetClock(window.resetsAt)
  const countdown = untilReset(window.resetsAt)
  return <div className={`quota-row sev-${window.severity}`}>
    <div className="quota-head">
      <strong>{window.label}</strong>
      <div className="quota-value"><strong>{Math.round(remaining)}%</strong><span>剩余</span></div>
    </div>
    <div className="progress-track"><span style={{ width: `${remaining}%` }} /></div>
    <div className="quota-foot">
      {clock ? <span className="reset-at" title={new Date(window.resetsAt as string).toLocaleString('zh-CN')}>{clock} 重置</span> : <span className="reset-at muted">滚动窗口</span>}
      {countdown && <span className="reset-countdown">{countdown}</span>}
    </div>
  </div>
}

function AccountCard({ account, onRefresh }: { account: Record<string, any>; onRefresh: () => void }) {
  const [confirming, setConfirming] = useState(false)
  const [resetting, setResetting] = useState(false)
  const [result, setResult] = useState<{ tone: 'success' | 'error'; title: string; description?: string; detail?: string } | null>(null)
  const provider = PROVIDERS[String(account.type)] || { label: String(account.type || '未知渠道'), logo: '?', className: 'unknown' }
  const accountName = String(account.email || account.name || account.auth_index)

  // Claude 的 banked reset 与 Codex 的主动重置是同一套交互，仅端点与文案按渠道切换。
  const resetProvider = account.type === 'claude' ? 'claude' : account.type === 'codex' ? 'codex' : null
  const resetLabel = resetProvider === 'claude' ? 'Claude' : 'Codex'

  const runReset = async () => {
    setResetting(true)
    try {
      if (resetProvider === 'claude') await api.resetClaudeQuota(String(account.auth_index))
      else await api.resetCodexQuota(String(account.auth_index))
      setConfirming(false)
      setResult({ tone: 'success', title: '重置成功', description: `已重置「${accountName}」的 ${resetLabel} 额度，消耗 1 次主动重置次数。` })
      onRefresh()
    } catch (error) {
      setConfirming(false)
      setResult({
        tone: 'error',
        title: '重置失败',
        description: `「${accountName}」的 ${resetLabel} 额度未被重置，主动重置次数未消耗。`,
        detail: error instanceof Error ? error.message : String(error),
      })
    } finally {
      setResetting(false)
    }
  }
  const quota: AccountQuota = account.normalizedQuota || { plan: '', tier: '', resetCredits: null, windows: [], error: null }
  const worst = quota.windows.reduce<QuotaWindow | null>(
    (peak, window) => (!peak || window.usedPercent > peak.usedPercent ? window : peak),
    null,
  )
  return <article className={`account-card ${provider.className}`}>
    <header>
      <div className="account-logo">{provider.logo}</div>
      <div><span className="provider-name">{provider.label}</span><h2>{account.email || account.account || account.name}</h2></div>
      <span className={account.disabled ? 'status-chip' : 'status-chip success'}>{account.disabled ? '已停用' : '运行中'}</span>
    </header>
    <div className="account-meta">
      <span><ShieldCheck size={15} />OAuth 已连接</span>
      <span><Activity size={15} />{String(account.status || 'ready')}</span>
      {quota.plan && <span className="plan-chip">{quota.plan}</span>}
      {quota.tier && <span className="tier-chip"><Crown size={12} />{quota.tier}</span>}
      {worst && worst.severity !== 'normal' && <span className={`sev-chip ${worst.severity}`}><TriangleAlert size={13} />{worst.severity === 'critical' ? '额度紧张' : '接近上限'}</span>}
    </div>
    {quota.resetCredits && <div className="reset-credits">
      <div className="reset-credits-head">
        <RotateCcw size={14} />
        <span>主动重置次数 <strong>{quota.resetCredits.available}</strong></span>
        <button
          className="secondary-button tiny"
          disabled={resetting || quota.resetCredits.available <= 0}
          onClick={() => setConfirming(true)}
        ><RotateCcw size={13} className={resetting ? 'spin' : ''} />{resetting ? '重置中' : '重置额度'}</button>
      </div>
      {quota.resetCredits.entries.length > 0 && <div className="reset-credit-list">
        {quota.resetCredits.entries.map((entry, index) => <div key={entry.id || index}>
          <span>第 {index + 1} 次</span><strong>{expiryClock(entry.expiresAt)} 过期</strong>
        </div>)}
      </div>}
    </div>}
    <div className="quota-stack">{quota.windows.map((window) => <QuotaRow key={window.id} window={window} />)}</div>
    {quota.error && <p className="quota-error"><TriangleAlert size={14} />{quota.error}</p>}
    {!quota.error && !quota.windows.length && <p className="quota-empty">上游未返回额度窗口</p>}
    {confirming && resetProvider && <ConfirmDialog
      title={`重置 ${resetLabel} 额度`}
      description={<>将消耗 <strong>1 次</strong>主动重置次数来重置该账号的 {resetLabel} 额度。此操作不可撤销。</>}
      target={accountName}
      confirmLabel="确认重置"
      busyLabel="重置中…"
      busy={resetting}
      onConfirm={runReset}
      onCancel={() => setConfirming(false)}
    />}
    {result && <ResultDialog {...result} onClose={() => setResult(null)} />}
  </article>
}

export function MonitorPage({ data, loading, onRefresh }: { data: MonitorData | null; loading: boolean; onRefresh: () => void }) {
  const accounts = data?.accounts || []
  const quotaShare = data?.quotaShare || null
  const groups = PROVIDER_ORDER
    .map((type) => ({ type, accounts: accounts.filter((account) => account.type === type) }))
    .filter((group) => group.accounts.length > 0)

  return <div className="page-stack">
    <section className="page-heading">
      <div><p className="eyebrow">UPSTREAM ACCOUNTS</p><h1>账号监控</h1><p>按渠道查看 AntiGravity、Claude 与 Codex OAuth 账号状态和额度重置时间。</p></div>
      <button className="secondary-button" onClick={onRefresh} disabled={loading}><RefreshCw size={16} className={loading ? 'spin' : ''} />刷新状态</button>
    </section>
    {groups.length > 0 && <section className="monitor-groups scroll-area fill" aria-label="上游账号分组">
      {groups.map((group) => <section className="monitor-provider-group" key={group.type} aria-labelledby={`monitor-group-${group.type}`}>
        <header className="monitor-group-head">
          <div><span className={`provider-orb ${group.type}`} /><h2 id={`monitor-group-${group.type}`}>{PROVIDERS[group.type].label}</h2></div>
          <span>{group.accounts.length} 个账号</span>
        </header>
        <div className="monitor-grid">{group.accounts.map((account) => <AccountCard key={String(account.id || account.auth_index || account.name)} account={account} onRefresh={onRefresh} />)}</div>
        <QuotaShareList share={quotaShare?.[group.type as 'codex' | 'claude' | 'antigravity']} />
      </section>)}
    </section>}
    {!accounts.length && <section className="panel empty-state"><Cloud size={30} /><h3>暂未读取到账号</h3><p>确认 CPA 中已导入 AntiGravity、Claude 或 Codex OAuth 凭据。</p></section>}
  </div>
}

// src/pages/MonitorPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { TxCard } from '@talex-touch/tuffex/card'
import { TxButton } from '@talex-touch/tuffex/button'
import { TxStatusBadge } from '@talex-touch/tuffex/status-badge'
import { TxEmptyState } from '@talex-touch/tuffex/empty-state'
import { TxAlert } from '@talex-touch/tuffex/alert'
import PageHeader from '../components/PageHeader.vue'
import ErrorPanel from '../components/ErrorPanel.vue'
import LoadingBlock from '../components/LoadingBlock.vue'
import { api } from '../api'
import { confirm } from '../lib/confirm'
import { useResource } from '../lib/resource'
import { fmtClock, fmtCompact, fmtCountdown, fmtPercent } from '../lib/format'
import type { MonitorData } from '../types'

/**
 * 上游账号与额度监控。
 * 读取走 useResource：失败给持久错误态 + 重试（原来 `catch {}` 把失败吞成「没有账号」）。
 * 额度重置改走全局 `await confirm()`（红队 D26/D31：同一类不可逆操作不再各写一套弹窗）。
 */
const res = useResource(() => api.monitor<MonitorData>(), [])
const loadMonitor = () => res.reload()
const currentData = computed(() => res.data.value)
const accounts = computed(() => currentData.value?.accounts || [])
const quotaShare = computed(() => currentData.value?.quotaShare || null)

const resetting = ref(false)
const resultNotice = ref<{ type: 'success' | 'warning' | 'danger'; message: string } | null>(null)

const PROVIDERS: Record<string, { label: string; logo: string; color: string }> = {
  claude: { label: 'Claude', logo: 'AI', color: '#d97757' },
  codex: { label: 'Codex', logo: 'O', color: '#10b981' },
  antigravity: { label: 'AntiGravity', logo: 'AG', color: '#84cc16' },
}

const PROVIDER_ORDER = ['antigravity', 'claude', 'codex']

const providerGroups = computed(() => {
  return PROVIDER_ORDER
    .map(type => ({
      type,
      accounts: accounts.value.filter(a => a.type === type),
    }))
    .filter(g => g.accounts.length > 0)
})

/** 倒计时与重置时刻都按固定时区渲染（src/lib/format.ts），不再跟浏览器时区走。 */
function untilReset(resetsAt: string | null): string {
  if (!resetsAt) return ''
  const target = new Date(resetsAt).getTime()
  if (Number.isNaN(target)) return ''
  const text = fmtCountdown(target - Date.now())
  return text === '即将重置' ? text : `还有 ${text}`
}

function resetClock(resetsAt: string | null) {
  return resetsAt ? fmtClock(resetsAt) : ''
}

function compactTokens(value: number) {
  return fmtCompact(value)
}

async function resetQuota(account: any) {
  const name = account.email || account.name
  const ok = await confirm({
    title: '重置账号窗口配额',
    body: `将消耗 1 次主动重置额度，重置账号「${name}」的窗口配额。此操作不可逆。`,
    confirmText: '重置额度',
    danger: true,
  })
  if (!ok) return
  resetting.value = true
  resultNotice.value = null
  try {
    if (account.type === 'claude') {
      await api.resetClaudeQuota(String(account.auth_index))
    } else {
      await api.resetCodexQuota(String(account.auth_index))
    }
    resultNotice.value = { type: 'success', message: `已成功重置「${name}」的额度。` }
    await loadMonitor()
  } catch (e) {
    resultNotice.value = { type: 'danger', message: `额度重置失败：${e instanceof Error ? e.message : '未知错误'}` }
  } finally {
    resetting.value = false
  }
}
</script>

<template>
  <div class="page-stack monitor-page">
    <PageHeader
      title="上游账号与额度监控"
      description="按渠道查看 AntiGravity、Claude 与 Codex 官方 OAuth 账号健康度、额度重置倒计时与窗口占用。"
    >
      <template #actions>
        <TxButton variant="secondary" :loading="res.loading.value" @click="loadMonitor">
          刷新状态
        </TxButton>
      </template>
    </PageHeader>

    <TxAlert v-if="resultNotice" :type="resultNotice.type" :closable="true" @close="resultNotice = null">
      {{ resultNotice.message }}
    </TxAlert>

    <!-- 失败：可读原因 + 重试；首次加载：骨架；其余：保留旧数据继续渲染 -->
    <ErrorPanel v-if="res.error.value" :error="res.error.value" :retry="loadMonitor" />
    <LoadingBlock v-else-if="!currentData" :lines="6" label="正在读取上游账号状态" />

    <!-- 账号分组 -->
    <div v-else-if="providerGroups.length" class="provider-groups-stack">
      <div v-for="g in providerGroups" :key="g.type" class="group-section">
        <div class="group-header">
          <div class="group-title-line">
            <span class="provider-dot" :style="{ background: PROVIDERS[g.type]?.color }" />
            <h2>{{ PROVIDERS[g.type]?.label || g.type }}</h2>
          </div>
          <span class="text-muted text-xs">{{ g.accounts.length }} 个接入账号</span>
        </div>

        <!-- 账号卡片网格 -->
        <div class="accounts-grid">
          <TxCard v-for="acc in g.accounts" :key="String(acc.id || acc.auth_index || acc.name)" class="account-card" :padding="16">
            <div class="account-card-header">
              <div class="acc-avatar" :style="{ background: `${PROVIDERS[g.type]?.color}1a`, color: PROVIDERS[g.type]?.color }">
                {{ PROVIDERS[g.type]?.logo || 'AI' }}
              </div>
              <div class="acc-info">
                <span class="acc-email" :title="acc.email || acc.name">{{ acc.email || acc.name }}</span>
                <span class="acc-meta text-muted">
                  {{ acc.type }} · {{ acc.status || 'ready' }}
                  <em v-if="acc.normalizedQuota?.plan" class="plan-tag">{{ acc.normalizedQuota.plan }}</em>
                </span>
              </div>
              <TxStatusBadge :status="acc.disabled ? 'info' : 'success'" :text="acc.disabled ? '已停用' : '运行中'" size="sm" />
            </div>

            <!-- 主动重置可用次数 -->
            <div v-if="acc.normalizedQuota?.resetCredits" class="reset-box">
              <div class="reset-head">
                <span>主动重置次数: <strong>{{ acc.normalizedQuota.resetCredits.available }}</strong> 次</span>
                <TxButton
                  size="sm"
                  variant="outline"
                  :disabled="acc.normalizedQuota.resetCredits.available <= 0 || resetting"
                  :aria-label="`重置账号 ${acc.email || acc.name} 的窗口配额`"
                  @click="resetQuota(acc)"
                >
                  重置额度
                </TxButton>
              </div>
            </div>

            <!-- 额度窗口列表 -->
            <div class="windows-stack">
              <div v-for="w in (acc.normalizedQuota?.windows || [])" :key="w.id" class="window-item" :class="`sev-${w.severity}`">
                <div class="window-head">
                  <span class="window-label">{{ w.label }}</span>
                  <span class="window-rem mono">剩余 <strong>{{ Math.max(0, 100 - w.usedPercent) }}%</strong></span>
                </div>
                <div class="window-bar-wrap">
                  <span class="window-bar-fill" :style="{ width: `${Math.max(0, 100 - w.usedPercent)}%` }" />
                </div>
                <div class="window-foot text-xs text-muted">
                  <span>{{ w.resetsAt ? `${resetClock(w.resetsAt)} 重置` : '滚动重置' }}</span>
                  <span v-if="w.resetsAt" class="countdown-text">{{ untilReset(w.resetsAt) }}</span>
                </div>
              </div>
            </div>

            <!-- 错误提示 -->
            <div v-if="acc.normalizedQuota?.error" class="error-strip">
              <small>{{ acc.normalizedQuota.error }}</small>
            </div>
          </TxCard>
        </div>

        <!-- 本窗口各 Key 消耗占比 -->
        <TxCard v-if="quotaShare?.[g.type as 'codex' | 'claude' | 'antigravity']?.keys?.length" class="quota-share-card" :padding="14">
          <div class="share-head">
            <strong>本窗口各 Key 消耗占比</strong>
            <span class="text-xs text-muted">按全量 Token 体量统计</span>
          </div>
          <div class="share-list">
            <div
              v-for="k in quotaShare[g.type as 'codex' | 'claude' | 'antigravity'].keys.slice(0, 8)"
              :key="k.keyId || k.keyName"
              class="share-row"
            >
              <span class="share-name" :title="k.keyName">{{ k.keyName }}</span>
              <div class="share-bar-wrap">
                <span class="share-bar-fill" :style="{ width: `${Math.max(2, Math.round(k.share * 100))}%` }" />
              </div>
              <span class="share-pct mono">{{ fmtPercent(k.share) }}</span>
            </div>
          </div>
        </TxCard>
      </div>
    </div>

    <!-- 空状态 -->
    <TxCard v-else :padding="32">
      <TxEmptyState
        title="暂未接入上游监控账号"
        description="系统检测到当前尚未配置或读取到 AntiGravity、Claude 或 Codex 账号凭据。先在 OAuth 登录池接入一个账号，这里就会出现额度与健康度。"
        primary-action="前往 OAuth 登录池"
        @primary="$router.push('/oauth')"
      />
    </TxCard>
  </div>
</template>

<style scoped>
.monitor-page {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;
  min-width: 0;
}
.provider-groups-stack {
  display: flex;
  flex-direction: column;
  gap: 24px;
}
.group-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.group-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.group-title-line {
  display: flex;
  align-items: center;
  gap: 8px;
}
.group-title-line h2 {
  margin: 0;
  font-size: 16px;
  font-weight: 700;
  color: var(--tx-text-color-primary, #151b45);
}
.provider-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
}
.accounts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
  gap: 14px;
}
.account-card {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.account-card-header {
  display: flex;
  align-items: center;
  gap: 10px;
}
.acc-avatar {
  width: 38px;
  height: 38px;
  border-radius: 8px;
  display: grid;
  place-items: center;
  font-weight: 700;
  font-size: 14px;
  flex-shrink: 0;
}
.acc-info {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-width: 0;
}
.acc-email {
  font-size: 13px;
  font-weight: 600;
  color: var(--tx-text-color-primary, #151b45);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.acc-meta {
  font-size: 11px;
}
.plan-tag {
  font-style: normal;
  background: var(--tx-fill-color, #eceff8);
  padding: 1px 4px;
  border-radius: 4px;
  margin-left: 4px;
}
.reset-box {
  padding: 8px 10px;
  background: var(--tx-fill-color, #eceff8);
  border-radius: 6px;
  font-size: 12px;
}
.reset-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.windows-stack {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.window-item {
  padding: 8px 10px;
  border-radius: 6px;
  background: var(--tx-fill-color-light, #f8f9fd);
  border: 1px solid var(--tx-border-color, #d5daec);
  display: flex;
  flex-direction: column;
  gap: 5px;
}
.window-item.sev-critical {
  border-color: #ef4444;
  background: rgba(239, 68, 68, 0.05);
}
.window-item.sev-warning {
  border-color: #f59e0b;
  background: rgba(245, 158, 11, 0.05);
}
.window-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 12px;
}
.window-label {
  font-weight: 600;
}
.window-bar-wrap {
  height: 5px;
  border-radius: 999px;
  background: var(--tx-border-color, #d5daec);
  overflow: hidden;
}
.window-bar-fill {
  display: block;
  height: 100%;
  border-radius: 999px;
  background: #10b981;
  transition: width 0.3s ease;
}
.window-item.sev-critical .window-bar-fill {
  background: #ef4444;
}
.window-item.sev-warning .window-bar-fill {
  background: #f59e0b;
}
.window-foot {
  display: flex;
  justify-content: space-between;
}
.countdown-text {
  color: var(--tx-color-primary, #3346c8);
}
.error-strip {
  padding: 6px 10px;
  background: rgba(239, 68, 68, 0.1);
  color: #b91c1c;
  border-radius: 4px;
}
.quota-share-card {
  margin-top: 4px;
}
.share-head {
  display: flex;
  justify-content: space-between;
  font-size: 13px;
  margin-bottom: 8px;
}
.share-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.share-row {
  display: grid;
  grid-template-columns: 140px 1fr 60px;
  align-items: center;
  gap: 12px;
  font-size: 12px;
}
.share-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.share-bar-wrap {
  height: 5px;
  background: var(--tx-fill-color, #eceff8);
  border-radius: 999px;
  overflow: hidden;
}
.share-bar-fill {
  display: block;
  height: 100%;
  background: var(--tx-color-primary, #3346c8);
  border-radius: 999px;
}
.share-pct {
  text-align: right;
  color: var(--tx-text-color-secondary, #535b85);
}
.reset-confirm-body p {
  margin: 0;
  line-height: 1.6;
  font-size: 13.5px;
  color: var(--tx-text-color-primary, #151b45);
}
.text-xs { font-size: 11.5px; }
.text-muted { color: var(--tx-text-color-secondary, #535b85); }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
</style>
