// src/pages/OAuthPage.tsx
import { Check, Copy, ExternalLink, Globe, KeyRound, LoaderCircle, ShieldAlert, Sparkles, Terminal } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { api } from '../api'
import type { OAuthStartResult } from '../types'

type ProviderItem = {
  id: string
  name: string
  label: string
  desc: string
  hint: string
  placeholder: string
  isDeviceFlow?: boolean
}

const PROVIDERS: ProviderItem[] = [
  {
    id: 'codex',
    name: 'OpenAI Codex',
    label: 'OpenAI / Codex',
    desc: '通过 OAuth 流程登录 Codex 服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:1455/auth/callback?code=...（显示无法访问是正常的），请从地址栏复制完整 URL 或单独提取 code 粘贴提交。',
    placeholder: 'http://localhost:1455/auth/callback?code=...&state=...',
  },
  {
    id: 'claude',
    name: 'Anthropic (Claude)',
    label: 'Claude Pro / Team',
    desc: '通过 OAuth 流程登录 Anthropic (Claude) 服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:54545/callback?code=...（显示无法访问是正常的），请从地址栏复制完整 URL 或提取 code 粘贴提交。',
    placeholder: 'http://localhost:54545/callback?code=...&state=...',
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    label: 'Google Gemini',
    desc: '通过 OAuth 流程登录 Antigravity（Google 账号）服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:51121/oauth-callback?code=...，请从地址栏复制完整 URL 粘贴提交。',
    placeholder: 'http://localhost:51121/oauth-callback?code=...&state=...',
  },
  {
    id: 'kimi',
    name: 'Kimi 国内站（kimi.com）',
    label: 'Moonshot Kimi',
    desc: '通过设备授权登录 kimi.com 国内站，自动获取并保存认证文件。国内站与国际站账号不互通。',
    hint: '打开授权链接并在页面中输入设备码确认授权即可，无需手动提交回调。',
    placeholder: '',
    isDeviceFlow: true,
  },
  {
    id: 'kimi-ai',
    name: 'Kimi 国际站（kimi.ai）',
    label: 'Kimi Global',
    desc: '通过设备授权登录 kimi.ai 国际站，自动保存独立的 kimi-ai 认证文件。',
    hint: '打开授权链接并在页面中输入设备码确认授权即可，无需手动提交回调。',
    placeholder: '',
    isDeviceFlow: true,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    label: 'xAI Grok',
    desc: '通过设备授权或 OAuth 流程登录 xAI Grok 服务，自动获取并保存认证文件。',
    hint: '若显示设备码，请在打开的网页中输入确认；若跳转回环地址，可将地址栏完整 URL 粘贴提交。',
    placeholder: 'http://localhost:... 或输入页面 code',
    isDeviceFlow: true,
  },
  {
    id: 'devin',
    name: 'Cognition Devin',
    label: 'Devin AI',
    desc: '通过浏览器 OAuth 登录 Devin / Cognition，自动保存认证文件。请在 5 分钟内完成授权。',
    hint: '远程服务器模式：复制最终的完整 /callback?code=...&state=... URL 粘贴提交。',
    placeholder: 'http://127.0.0.1:8317/callback?code=...&state=...',
  },
  {
    id: 'meta',
    name: 'Meta AI (Muse)',
    label: 'Meta Muse',
    desc: '打开授权链接，如有提示请输入设备码。授权完成后将自动获取并保存认证文件。',
    hint: '打开授权链接并在页面中输入设备码确认授权。',
    placeholder: '',
    isDeviceFlow: true,
  },
]

type SessionState = {
  session: OAuthStartResult | null
  status: 'idle' | 'waiting' | 'success' | 'error'
  error?: string
  callbackUrl: string
  submittingCallback: boolean
  callbackStatus?: 'success' | 'error'
  copiedUrl?: boolean
  copiedCode?: boolean
}

export function OAuthPage({
  onNavigateChannels,
  onNotify,
}: {
  onNavigateChannels: () => void
  onNotify: (message: string) => void
}) {
  const [sessions, setSessions] = useState<Record<string, SessionState>>({})
  const pollTimers = useRef<Record<string, number>>({})

  const clearTimer = (provider: string) => {
    if (pollTimers.current[provider]) {
      window.clearInterval(pollTimers.current[provider])
      delete pollTimers.current[provider]
    }
  }

  useEffect(() => {
    return () => {
      // 清除所有轮询器
      Object.keys(pollTimers.current).forEach((p) => {
        window.clearInterval(pollTimers.current[p])
      })
      pollTimers.current = {}
    }
  }, [])

  const startLogin = async (item: ProviderItem) => {
    clearTimer(item.id)
    setSessions((prev) => ({
      ...prev,
      [item.id]: {
        session: null,
        status: 'waiting',
        callbackUrl: '',
        submittingCallback: false,
      },
    }))

    try {
      const result = await api.startOAuth(item.id)
      setSessions((prev) => ({
        ...prev,
        [item.id]: {
          ...(prev[item.id] || {}),
          session: result,
          status: 'waiting',
          error: undefined,
        },
      }))

      // 启动 2.5 秒一次的状态轮询
      pollTimers.current[item.id] = window.setInterval(async () => {
        try {
          const check = await api.getOAuthStatus(result.state)
          if (check.status === 'ok') {
            clearTimer(item.id)
            setSessions((prev) => ({
              ...prev,
              [item.id]: {
                ...(prev[item.id] || {}),
                status: 'success',
                error: undefined,
              },
            }))
            onNotify(`${item.name} 认证成功！凭证已保存至网关。`)
          } else if (check.status === 'error') {
            clearTimer(item.id)
            setSessions((prev) => ({
              ...prev,
              [item.id]: {
                ...(prev[item.id] || {}),
                status: 'error',
                error: check.error || '认证失败或会话已过期',
              },
            }))
          }
        } catch {
          // 偶发网络抖动忽略
        }
      }, 2500)
    } catch (err) {
      setSessions((prev) => ({
        ...prev,
        [item.id]: {
          session: null,
          status: 'error',
          error: err instanceof Error ? err.message : '发起授权失败',
          callbackUrl: '',
          submittingCallback: false,
        },
      }))
    }
  }

  const submitCallback = async (item: ProviderItem) => {
    const s = sessions[item.id]
    const raw = (s?.callbackUrl || '').trim()
    if (!raw) return
    setSessions((prev) => ({
      ...prev,
      [item.id]: { ...(prev[item.id] || {}), submittingCallback: true },
    }))

    try {
      await api.submitOAuthCallback(item.id, raw, s?.session?.state)
      setSessions((prev) => ({
        ...prev,
        [item.id]: {
          ...(prev[item.id] || {}),
          submittingCallback: false,
          callbackStatus: 'success',
        },
      }))
      onNotify('已提交回调，网关正在向上游验证并换取凭证...')
    } catch (err) {
      setSessions((prev) => ({
        ...prev,
        [item.id]: {
          ...(prev[item.id] || {}),
          submittingCallback: false,
          callbackStatus: 'error',
          error: err instanceof Error ? err.message : '提交回调失败',
        },
      }))
    }
  }

  const cancelLogin = async (item: ProviderItem) => {
    clearTimer(item.id)
    const state = sessions[item.id]?.session?.state
    if (state) {
      api.cancelOAuth(state).catch(() => {})
    }
    setSessions((prev) => ({
      ...prev,
      [item.id]: {
        session: null,
        status: 'idle',
        callbackUrl: '',
        submittingCallback: false,
      },
    }))
  }

  const copyText = async (item: ProviderItem, text: string, type: 'url' | 'code') => {
    try {
      await navigator.clipboard.writeText(text)
      setSessions((prev) => ({
        ...prev,
        [item.id]: {
          ...(prev[item.id] || {}),
          [type === 'url' ? 'copiedUrl' : 'copiedCode']: true,
        },
      }))
      setTimeout(() => {
        setSessions((prev) => ({
          ...prev,
          [item.id]: {
            ...(prev[item.id] || {}),
            [type === 'url' ? 'copiedUrl' : 'copiedCode']: false,
          },
        }))
      }, 1800)
    } catch {}
  }

  return (
    <div className="page-stack oauth-page">
      <section className="page-heading">
        <div>
          <p className="eyebrow">AUTHENTICATION</p>
          <h1>OAuth 授权登录</h1>
          <p>
            通过官方 OAuth 流程或设备码将上游提供商账号连接至小鸡云 CPA，凭据直接由网关安全接管并自动上线模型。
          </p>
        </div>
        <button type="button" className="secondary-button" onClick={onNavigateChannels}>
          <Globe size={16} />
          查看渠道与账号池
        </button>
      </section>

      <section className="panel fill">
        <div className="panel-title">
          <div>
            <h2>AI 提供商登录池</h2>
            <p>支持浏览器授权、回调链接回填与设备码确认；每个账号均可独立配置出口代理与模型开关。</p>
          </div>
          <span className="soft-badge">支持 {PROVIDERS.length} 种认证方式</span>
        </div>

        <div className="oauth-grid scroll-area">
          {PROVIDERS.map((item) => {
            const s = sessions[item.id] || { status: 'idle', callbackUrl: '', submittingCallback: false }
            const isWaiting = s.status === 'waiting'
            const isSuccess = s.status === 'success'
            const isError = s.status === 'error'

            return (
              <div
                className={`oauth-card ${isWaiting ? 'waiting' : ''} ${isSuccess ? 'success' : ''}`}
                key={item.id}
              >
                <div className="oauth-card-header">
                  <div className="header-left">
                    <span className="card-icon">
                      <KeyRound size={16} />
                    </span>
                    <strong>{item.name}</strong>
                  </div>
                  <span className="oauth-tag">{item.label}</span>
                </div>

                <p className="oauth-card-desc">{item.desc}</p>

                {/* 初始状态：显示开始登录按钮 */}
                {s.status === 'idle' && (
                  <div className="oauth-card-foot">
                    <button
                      type="button"
                      className="primary-button tiny"
                      onClick={() => startLogin(item)}
                    >
                      <Sparkles size={13} />
                      <span>开始登录</span>
                    </button>
                  </div>
                )}

                {/* 活跃会话状态（等待中、输入回调、错误重试） */}
                {s.status !== 'idle' && (
                  <div className="oauth-active-box">
                    {/* 状态徽标 */}
                    <div className="active-status-row">
                      {isWaiting && (
                        <div className="status-chip live-wait">
                          <LoaderCircle size={13} className="spin" />
                          <span>等待认证中...</span>
                        </div>
                      )}
                      {isSuccess && (
                        <div className="status-chip success">
                          <Check size={13} />
                          <span>认证成功！</span>
                        </div>
                      )}
                      {isError && (
                        <div className="status-chip danger">
                          <ShieldAlert size={13} />
                          <span>认证失败</span>
                        </div>
                      )}
                    </div>

                    {/* 设备码展示 */}
                    {s.session?.user_code && (
                      <div className="device-code-card">
                        <span className="code-label">设备授权码</span>
                        <div className="code-row">
                          <code className="code-val">{s.session.user_code}</code>
                          <button
                            type="button"
                            className="secondary-button tiny"
                            onClick={() => s.session?.user_code && copyText(item, s.session.user_code, 'code')}
                          >
                            {s.copiedCode ? <Check size={12} /> : <Copy size={12} />}
                            <span>{s.copiedCode ? '已复制' : '复制设备码'}</span>
                          </button>
                        </div>
                      </div>
                    )}

                    {/* 授权链接 */}
                    {s.session?.url && (
                      <div className="auth-url-card">
                        <div className="auth-url-actions">
                          <button
                            type="button"
                            className="primary-button tiny"
                            onClick={() => window.open(s.session?.url, '_blank', 'noopener,noreferrer')}
                          >
                            <ExternalLink size={13} />
                            <span>在浏览器中打开授权</span>
                          </button>
                          <button
                            type="button"
                            className="secondary-button tiny"
                            onClick={() => s.session?.url && copyText(item, s.session.url, 'url')}
                          >
                            {s.copiedUrl ? <Check size={12} /> : <Copy size={12} />}
                            <span>{s.copiedUrl ? '已复制' : '复制链接'}</span>
                          </button>
                        </div>
                      </div>
                    )}

                    {/* 回调 URL / 授权码输入区（对于需要重定向的提供商恒常展开） */}
                    {!item.isDeviceFlow && isWaiting && (
                      <div className="callback-section">
                        <div className="callback-label-row">
                          <strong>回调 URL 或授权码</strong>
                        </div>
                        <p className="callback-hint">{item.hint}</p>
                        <div className="callback-input-row">
                          <input
                            type="text"
                            className="callback-input"
                            placeholder={item.placeholder}
                            value={s.callbackUrl}
                            onChange={(e) =>
                              setSessions((prev) => ({
                                ...prev,
                                [item.id]: { ...(prev[item.id] || {}), callbackUrl: e.target.value },
                              }))
                            }
                          />
                          <button
                            type="button"
                            className="primary-button tiny"
                            disabled={s.submittingCallback || !s.callbackUrl.trim()}
                            onClick={() => submitCallback(item)}
                          >
                            {s.submittingCallback ? <LoaderCircle size={12} className="spin" /> : <Terminal size={12} />}
                            <span>提交回调</span>
                          </button>
                        </div>
                        {s.callbackStatus === 'success' && (
                          <small className="callback-success-text">✓ 回调已提交，请等待网关完成认证...</small>
                        )}
                      </div>
                    )}

                    {/* 错误提示 */}
                    {s.error && (
                      <div className="error-strip">
                        <ShieldAlert size={14} />
                        <span>{s.error}</span>
                      </div>
                    )}

                    {/* 底部按钮 */}
                    <div className="active-card-foot">
                      {isSuccess ? (
                        <>
                          <button type="button" className="primary-button tiny" onClick={onNavigateChannels}>
                            查看渠道账号
                          </button>
                          <button type="button" className="secondary-button tiny" onClick={() => cancelLogin(item)}>
                            登录另一个账号
                          </button>
                        </>
                      ) : (
                        <button type="button" className="secondary-button tiny" onClick={() => cancelLogin(item)}>
                          取消 / 重新开始
                        </button>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </section>
    </div>
  )
}

// src/pages/OAuthPage.vue
<script setup lang="ts">
import { ref, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { TxCard } from '@talex-touch/tuffex/card'
import { TxTag } from '@talex-touch/tuffex/tag'
import { TxButton } from '@talex-touch/tuffex/button'
import { TxInput } from '@talex-touch/tuffex/input'
import { TxAlert } from '@talex-touch/tuffex/alert'
import { toast } from '@talex-touch/tuffex/utils'
import { api } from '../api'
import type { OAuthStartResult } from '../types'

defineProps<{
  onNavigateChannels?: () => void
}>()

const emit = defineEmits<{
  (e: 'navigate-channels'): void
  (e: 'notify', msg: string): void
}>()

const router = useRouter()

type ProviderItem = {
  id: string
  name: string
  label: string
  desc: string
  hint: string
  placeholder: string
  isDeviceFlow?: boolean
  icon: string
}

const PROVIDERS: ProviderItem[] = [
  {
    id: 'codex',
    name: 'OpenAI Codex',
    label: 'OpenAI / Codex',
    desc: '通过 OAuth 流程登录 Codex 服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:1455/auth/callback?code=...，请从地址栏复制完整 URL 粘贴提交。',
    placeholder: 'http://localhost:1455/auth/callback?code=...&state=...',
    icon: 'i-carbon-logo-github text-emerald-600',
  },
  {
    id: 'claude',
    name: 'Anthropic (Claude)',
    label: 'Claude Pro / Team',
    desc: '通过 OAuth 流程登录 Anthropic (Claude) 服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:54545/callback?code=...，请从地址栏复制完整 URL 粘贴提交。',
    placeholder: 'http://localhost:54545/callback?code=...&state=...',
    icon: 'i-carbon-bot text-amber-600',
  },
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    label: 'Google Gemini',
    desc: '通过 OAuth 流程登录 Antigravity（Google 账号）服务，自动获取并保存认证文件。',
    hint: '远程服务器模式：在浏览器授权后页面会跳转到 http://localhost:51121/oauth-callback?code=...，请从地址栏复制完整 URL 粘贴提交。',
    placeholder: 'http://localhost:51121/oauth-callback?code=...&state=...',
    icon: 'i-carbon-logo-google text-blue-600',
  },
  {
    id: 'kimi',
    name: 'Kimi 国内站（kimi.com）',
    label: 'Moonshot Kimi',
    desc: '通过设备授权登录 kimi.com 国内站，自动获取并保存认证文件。国内站与国际站账号不互通。',
    hint: '打开授权链接并在页面中输入设备码确认授权即可，无需手动提交回调。',
    placeholder: '',
    isDeviceFlow: true,
    icon: 'i-carbon-moon text-indigo-600',
  },
  {
    id: 'kimi-ai',
    name: 'Kimi 国际站（kimi.ai）',
    label: 'Kimi Global',
    desc: '通过设备授权登录 kimi.ai 国际站，自动保存独立的 kimi-ai 认证文件。',
    hint: '打开授权链接并在页面中输入设备码确认授权即可，无需手动提交回调。',
    placeholder: '',
    isDeviceFlow: true,
    icon: 'i-carbon-earth-southeast-asia text-cyan-600',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    label: 'xAI Grok',
    desc: '通过设备授权或 OAuth 流程登录 xAI Grok 服务，自动获取并保存认证文件。',
    hint: '若显示设备码，请在打开的网页中输入确认；若跳转回环地址，可将地址栏完整 URL 粘贴提交。',
    placeholder: 'http://localhost:... 或输入页面 code',
    isDeviceFlow: true,
    icon: 'i-carbon-terminal text-neutral-600',
  },
  {
    id: 'devin',
    name: 'Cognition Devin',
    label: 'Devin AI',
    desc: '通过浏览器 OAuth 登录 Devin / Cognition，自动保存认证文件。请在 5 分钟内完成授权。',
    hint: '远程服务器模式：复制最终的完整 /callback?code=...&state=... URL 粘贴提交。',
    placeholder: 'http://127.0.0.1:8317/callback?code=...&state=...',
    icon: 'i-carbon-machine-learning text-purple-600',
  },
  {
    id: 'meta',
    name: 'Meta AI (Muse)',
    label: 'Meta Muse',
    desc: '打开授权链接，如有提示请输入设备码。授权完成后将自动获取并保存认证文件。',
    hint: '打开授权链接并在页面中输入设备码确认授权。',
    placeholder: '',
    isDeviceFlow: true,
    icon: 'i-carbon-virtual-column-key text-pink-600',
  },
]

type SessionState = {
  session: OAuthStartResult | null
  status: 'idle' | 'waiting' | 'success' | 'error'
  error?: string
  callbackUrl: string
  submittingCallback: boolean
}

const sessions = ref<Record<string, SessionState>>({})
const pollTimers = ref<Record<string, number>>({})

function getSession(id: string): SessionState {
  if (!sessions.value[id]) {
    sessions.value[id] = {
      session: null,
      status: 'idle',
      callbackUrl: '',
      submittingCallback: false,
    }
  }
  return sessions.value[id]
}

function clearPoll(id: string) {
  if (pollTimers.value[id]) {
    window.clearInterval(pollTimers.value[id])
    delete pollTimers.value[id]
  }
}

async function startLogin(item: ProviderItem) {
  clearPoll(item.id)
  const s = getSession(item.id)
  s.status = 'waiting'
  s.error = ''
  s.callbackUrl = ''

  try {
    const res = await api.startOAuth(item.id)
    s.session = res

    // Open auth URL in window
    if (res.url) {
      window.open(res.url, '_blank', 'noopener,noreferrer')
    }

    // Start polling
    pollTimers.value[item.id] = window.setInterval(async () => {
      try {
        const statusRes = await api.getOAuthStatus(res.state)
        if (statusRes.status === 'ok') {
          clearPoll(item.id)
          s.status = 'success'
          toast({ title: '授权成功', description: `${item.name} 凭据已安全保存`, variant: 'success' })
        } else if (statusRes.status === 'error') {
          clearPoll(item.id)
          s.status = 'error'
          s.error = statusRes.error || '授权失败，会话已终止'
          toast({ title: '授权失败', description: s.error, variant: 'danger' })
        }
      } catch {
        // network jitter during polling
      }
    }, 3000)
  } catch (err) {
    s.status = 'error'
    s.error = err instanceof Error ? err.message : '发起登录失败'
    toast({ title: '发起登录失败', description: s.error, variant: 'danger' })
  }
}

async function submitCallback(item: ProviderItem) {
  const s = getSession(item.id)
  if (!s.callbackUrl.trim()) {
    toast({ title: '请输入回调链接', variant: 'warning' })
    return
  }

  s.submittingCallback = true
  try {
    await api.submitOAuthCallback(item.id, s.callbackUrl.trim(), s.session?.state)
    clearPoll(item.id)
    s.status = 'success'
    toast({ title: '回调提交成功', description: `${item.name} 账号已绑定并就绪`, variant: 'success' })
  } catch (err) {
    s.error = err instanceof Error ? err.message : '提交回调失败'
    toast({ title: '提交回调失败', description: s.error, variant: 'danger' })
  } finally {
    s.submittingCallback = false
  }
}

async function cancelLogin(item: ProviderItem) {
  clearPoll(item.id)
  const s = getSession(item.id)
  const state = s.session?.state
  s.status = 'idle'
  s.session = null
  s.callbackUrl = ''
  if (state) {
    try {
      await api.cancelOAuth(state)
    } catch {
      // ignore
    }
  }
  toast({ title: '已取消登录', variant: 'info' })
}

function copyText(text: string, title = '已复制') {
  void navigator.clipboard.writeText(text)
  toast({ title, variant: 'success' })
}

function handleGoChannels() {
  emit('navigate-channels')
  router.push('/channels')
}

onUnmounted(() => {
  Object.keys(pollTimers.value).forEach((id) => clearPoll(id))
})
</script>

<template>
  <div class="page">
    <!-- 头部横幅 -->
    <header class="page-head">
      <div class="page-head__text">
        <div class="eyebrow-tag">AUTHENTICATION</div>
        <h1>OAuth 授权登录</h1>
        <p>通过官方 OAuth 授权或设备码机制将上游供应商账号连接至网关，安全接管并上线模型矩阵。</p>
      </div>
      <div class="page-head__actions">
        <TxButton variant="secondary" icon="i-carbon-network-4" @click="handleGoChannels">
          查看渠道与账号池
        </TxButton>
      </div>
    </header>

    <div class="oauth-section-title">
      <div>
        <h2 class="section-title">AI 提供商登录池</h2>
        <span class="muted text-12">支持浏览器授权、回调回填与设备码确认；每个账号均可独立配置出口代理。</span>
      </div>
      <TxTag size="sm" variant="soft" color="var(--tx-color-primary)" :label="`支持 ${PROVIDERS.length} 种认证方式`" />
    </div>

    <!-- 登录卡片网格 -->
    <div class="oauth-grid">
      <TxCard
        v-for="item in PROVIDERS"
        :key="item.id"
        class="oauth-card"
        :class="{
          'card-waiting': getSession(item.id).status === 'waiting',
          'card-success': getSession(item.id).status === 'success',
        }"
      >
        <!-- 卡片头部 -->
        <div class="card-top-head">
          <div class="provider-title-row">
            <span :class="item.icon" class="provider-icon" />
            <strong class="provider-name">{{ item.name }}</strong>
          </div>
          <TxTag size="sm" variant="outline" :label="item.label" />
        </div>

        <p class="provider-desc">{{ item.desc }}</p>

        <!-- 初始空闲状态 -->
        <div v-if="getSession(item.id).status === 'idle'" class="card-idle-footer">
          <TxButton
            variant="primary"
            size="sm"
            icon="i-carbon-login"
            @click="startLogin(item)"
          >
            开始登录
          </TxButton>
        </div>

        <!-- 等待授权状态 -->
        <div v-else-if="getSession(item.id).status === 'waiting'" class="card-waiting-body">
          <!-- 设备码展示 -->
          <div v-if="item.isDeviceFlow && getSession(item.id).session?.user_code" class="device-code-box">
            <span class="muted text-11">请在授权页中输入此设备码：</span>
            <div class="code-copy-row">
              <strong class="mono code-highlight">{{ getSession(item.id).session?.user_code }}</strong>
              <TxButton
                size="sm"
                variant="secondary"
                icon="i-carbon-copy"
                @click="copyText(getSession(item.id).session?.user_code || '', '设备码已复制')"
              />
            </div>
          </div>

          <!-- 授权链接按钮 -->
          <div class="link-actions-box">
            <TxButton
              variant="secondary"
              size="sm"
              icon="i-carbon-launch"
              @click="window.open(getSession(item.id).session?.url || '', '_blank')"
            >
              打开授权页面
            </TxButton>
            <TxButton
              variant="secondary"
              size="sm"
              icon="i-carbon-copy"
              @click="copyText(getSession(item.id).session?.url || '', '授权链接已复制')"
            >
              复制链接
            </TxButton>
          </div>

          <!-- 轮询状态条 -->
          <div class="polling-indicator">
            <span class="i-carbon-circle-dash spin text-16 text-blue-600" />
            <span class="text-12">正在等待授权确认...（自动轮询中）</span>
          </div>

          <!-- 回调回填输入 -->
          <div v-if="!item.isDeviceFlow" class="callback-section">
            <small class="muted text-11">{{ item.hint }}</small>
            <div class="callback-input-row">
              <TxInput
                v-model="getSession(item.id).callbackUrl"
                :placeholder="item.placeholder"
              />
              <TxButton
                variant="primary"
                size="sm"
                :loading="getSession(item.id).submittingCallback"
                @click="submitCallback(item)"
              >
                提交回调
              </TxButton>
            </div>
          </div>

          <div class="cancel-row">
            <TxButton variant="ghost" size="sm" @click="cancelLogin(item)">取消登录</TxButton>
          </div>
        </div>

        <!-- 成功状态 -->
        <div v-else-if="getSession(item.id).status === 'success'" class="card-success-body">
          <span class="i-carbon-checkmark-filled text-28 text-emerald-600" />
          <strong>授权成功！</strong>
          <small class="muted text-12">账号凭据已安全持久化并生效到渠道池中。</small>
          <TxButton variant="primary" size="sm" @click="getSession(item.id).status = 'idle'">
            完成并关闭
          </TxButton>
        </div>

        <!-- 失败状态 -->
        <div v-else-if="getSession(item.id).status === 'error'" class="card-error-body">
          <TxAlert
            variant="danger"
            title="授权未完成"
            :description="getSession(item.id).error || '遇到错误，请重新尝试'"
          />
          <div class="error-actions-row">
            <TxButton variant="secondary" size="sm" @click="getSession(item.id).status = 'idle'">返回</TxButton>
            <TxButton variant="primary" size="sm" @click="startLogin(item)">重新发起</TxButton>
          </div>
        </div>
      </TxCard>
    </div>
  </div>
</template>

<style scoped>
.oauth-section-title {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 4px;
  margin-bottom: 8px;
}

.oauth-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
  gap: 16px;
}

.oauth-card {
  display: flex;
  flex-direction: column;
  transition: all 0.2s ease;
}

.card-waiting {
  border-color: var(--tx-color-primary);
  box-shadow: 0 0 0 1px var(--tx-color-primary);
}

.card-success {
  border-color: var(--tx-color-success);
}

.card-top-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
}

.provider-title-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.provider-icon {
  font-size: 20px;
}

.provider-name {
  font-size: 14.5px;
  color: var(--tx-text-color-primary);
}

.provider-desc {
  font-size: 12.5px;
  line-height: 1.5;
  color: var(--tx-text-color-secondary);
  margin: 10px 0 14px 0;
  flex: 1;
}

.card-idle-footer {
  display: flex;
  justify-content: flex-end;
  margin-top: auto;
}

.card-waiting-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 12px;
  background: var(--tx-fill-color-light);
  border-radius: var(--tx-border-radius-base);
}

.device-code-box {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.code-copy-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.code-highlight {
  font-size: 16px;
  letter-spacing: 0.1em;
  padding: 4px 8px;
  background: var(--tx-bg-color);
  border: 1px dashed var(--tx-border-color);
  border-radius: 4px;
  color: var(--tx-color-primary);
}

.link-actions-box {
  display: flex;
  gap: 8px;
}

.polling-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  background: var(--tx-bg-color);
  border-radius: var(--tx-border-radius-small);
}

.callback-section {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.callback-input-row {
  display: flex;
  gap: 8px;
}

.callback-input-row :deep(.tuff-input-wrap) {
  flex: 1;
}

.cancel-row {
  display: flex;
  justify-content: flex-end;
}

.card-success-body {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 20px;
  gap: 8px;
}

.card-error-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.error-actions-row {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
</style>
